SELECT GETDATE() AS [Date], 'Current Date.' UNION ALL
SELECT CAST(GETDATE() AS DATETIME) - CAST('00:15' AS DATETIME), 'Subtracts 15 minutes.' UNION ALL
SELECT CAST(GETDATE() AS DATETIME) + CAST('00:15' AS DATETIME), 'Add 15 minutes.' UNION ALL
SELECT DATEADD(DAY, 1, GETDATE()), 'Add 1 day.' UNION ALL
SELECT DATEADD(WEEK, 1, GETDATE()), 'Add 1 week.' UNION ALL
SELECT DATEADD(MONTH, 1, GETDATE()), 'Add 1 month.' UNION ALL
SELECT DATEADD(YEAR, 1, GETDATE()), 'Add 1 year.'
